# Generated by Django 4.1.7 on 2023-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
