# Generated by Django 4.1.7 on 2023-04-09 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.CharField(default='Nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='com_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do comentário'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da publicação'),
        ),
    ]
