# Generated by Django 4.1.7 on 2023-04-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario_nome_alter_comentario_com_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
